export { BaseAppClient, ProxyError } from "./base-app-client.js";
export { JiraClient } from "./jira-client.js";
export type { JiraSite, JiraIssue, JiraProject, JiraTransition, JiraSearchResult } from "./jira-client.js";
export { GitLabClient } from "./gitlab-client.js";
export type { GitLabUser, GitLabProject, GitLabMergeRequest, GitLabIssue, GitLabPipeline } from "./gitlab-client.js";
export { GitHubClient } from "./github-client.js";
export type { GitHubRepo, GitHubIssue, GitHubPullRequest, GitHubWorkflowRun } from "./github-client.js";
export { OutlookClient } from "./outlook-client.js";
export type { OutlookMessage, OutlookMailFolder } from "./outlook-client.js";
export { MsTodoClient } from "./ms-todo-client.js";
export type { MsTodoList, MsTodoTask } from "./ms-todo-client.js";
export { GmailClient } from "./gmail-client.js";
export type { GmailMessage, GmailMessageListItem, GmailLabel } from "./gmail-client.js";
export { GoogleTasksClient } from "./google-tasks-client.js";
export type { GoogleTaskList, GoogleTask } from "./google-tasks-client.js";
export { NotionClient } from "./notion-client.js";
export type { NotionPage, NotionDatabase, NotionBlock, NotionSearchResult } from "./notion-client.js";
export { ConfluenceClient } from "./confluence-client.js";
export type { ConfluenceSite, ConfluenceSpace, ConfluencePage } from "./confluence-client.js";
export { OutlookCalendarClient } from "./outlook-calendar-client.js";
export type { OutlookCalendar, OutlookEvent } from "./outlook-calendar-client.js";
